[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"

# Functions configuration
[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"